# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: project_1.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fproject_1.proto\x12\tproject_1\",\n\tvariables\x12\t\n\x01\x61\x18\x01 \x01(\x01\x12\t\n\x01\x62\x18\x02 \x01(\x01\x12\t\n\x01\x63\x18\x03 \x01(\x01\" \n\x0bx_solutions\x12\x11\n\tsolutions\x18\x01 \x01(\t2R\n\x0fQuadraticSolver\x12?\n\x0fQuadraticSolver\x12\x14.project_1.variables\x1a\x16.project_1.x_solutionsb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'project_1_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_VARIABLES']._serialized_start=30
  _globals['_VARIABLES']._serialized_end=74
  _globals['_X_SOLUTIONS']._serialized_start=76
  _globals['_X_SOLUTIONS']._serialized_end=108
  _globals['_QUADRATICSOLVER']._serialized_start=110
  _globals['_QUADRATICSOLVER']._serialized_end=192
# @@protoc_insertion_point(module_scope)
