# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import project_1_pb2 as project__1__pb2


class QuadraticSolverStub(object):
    """solving the Quadratic equation
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.QuadraticSolver = channel.unary_unary(
                '/project_1.QuadraticSolver/QuadraticSolver',
                request_serializer=project__1__pb2.variables.SerializeToString,
                response_deserializer=project__1__pb2.x_solutions.FromString,
                )


class QuadraticSolverServicer(object):
    """solving the Quadratic equation
    """

    def QuadraticSolver(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_QuadraticSolverServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'QuadraticSolver': grpc.unary_unary_rpc_method_handler(
                    servicer.QuadraticSolver,
                    request_deserializer=project__1__pb2.variables.FromString,
                    response_serializer=project__1__pb2.x_solutions.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'project_1.QuadraticSolver', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class QuadraticSolver(object):
    """solving the Quadratic equation
    """

    @staticmethod
    def QuadraticSolver(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/project_1.QuadraticSolver/QuadraticSolver',
            project__1__pb2.variables.SerializeToString,
            project__1__pb2.x_solutions.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
